import { Flight } from '@/types/flight';

// Mock flight data for development/testing when API is unavailable
// Note: timestamps are generated dynamically when this data is returned from the API
export const mockFlights: Flight[] = [
    {
        flight_id: 'mock-1',
        callsign: 'SAS123',
        flight_number: 'SK123',
        flight: 'SK123',
        lat: 59.75,
        lon: 17.95,
        latitude: 59.75,
        longitude: 17.95,
        track: 45,
        heading: 45,
        altitude: 35000,
        alt: 35000,
        gspeed: 450,
        vspeed: 0,  // Level flight (0 * 64 = 0 ft/min)
        squawk: '1234',
        type: 'A320',
        registration: 'SE-ABC',
        reg: 'SE-ABC',
        origin_airport_iata: 'ARN',
        destination_airport_iata: 'CPH',
        orig_iata: 'ARN',
        dest_iata: 'CPH',
        airline_iata: 'SK',
        airline_icao: 'SAS',
        operating_as: 'SAS',
        fr24_id: 'mock-fr24-1'
    },
    {
        flight_id: 'mock-2',
        callsign: 'DLH456',
        flight_number: 'LH456',
        flight: 'LH456',
        lat: 59.70,
        lon: 18.10,
        latitude: 59.70,
        longitude: 18.10,
        track: 180,
        heading: 180,
        altitude: 28000,
        alt: 28000,
        gspeed: 420,
        vspeed: -8,  // Descending (-8 * 64 = -512 ft/min)
        squawk: '2345',
        type: 'B738',
        registration: 'D-ABCD',
        reg: 'D-ABCD',
        origin_airport_iata: 'FRA',
        destination_airport_iata: 'ARN',
        orig_iata: 'FRA',
        dest_iata: 'ARN',
        airline_iata: 'LH',
        airline_icao: 'DLH',
        operating_as: 'DLH',
        fr24_id: 'mock-fr24-2'
    },
    {
        flight_id: 'mock-3',
        callsign: 'NAX789',
        flight_number: 'DY789',
        flight: 'DY789',
        lat: 59.60,
        lon: 17.80,
        latitude: 59.60,
        longitude: 17.80,
        track: 270,
        heading: 270,
        altitude: 32000,
        alt: 32000,
        gspeed: 440,
        vspeed: 25,  // Climbing (25 * 64 = 1600 ft/min)
        squawk: '3456',
        type: 'B737',
        registration: 'LN-XYZ',
        reg: 'LN-XYZ',
        origin_airport_iata: 'OSL',
        destination_airport_iata: 'ARN',
        orig_iata: 'OSL',
        dest_iata: 'ARN',
        airline_iata: 'DY',
        airline_icao: 'NAX',
        operating_as: 'NAX',
        fr24_id: 'mock-fr24-3'
    },
    {
        flight_id: 'mock-4',
        callsign: 'BAW321',
        flight_number: 'BA321',
        flight: 'BA321',
        lat: 59.80,
        lon: 18.20,
        latitude: 59.80,
        longitude: 18.20,
        track: 90,
        heading: 90,
        altitude: 38000,
        alt: 38000,
        gspeed: 480,
        vspeed: -3,  // Slight descent (-3 * 64 = -192 ft/min)
        squawk: '4567',
        type: 'A321',
        registration: 'G-EFGH',
        reg: 'G-EFGH',
        origin_airport_iata: 'LHR',
        destination_airport_iata: 'ARN',
        orig_iata: 'LHR',
        dest_iata: 'ARN',
        airline_iata: 'BA',
        airline_icao: 'BAW',
        operating_as: 'BAW',
        fr24_id: 'mock-fr24-4'
    }
];
