import { Flight } from '@/types/flight';

// Mock flight data for development/testing when API is unavailable
export const mockFlights: Flight[] = [
    {
        flight_id: 'mock-1',
        callsign: 'SAS123',
        flight_number: 'SK123',
        flight: 'SK123',
        lat: 59.75,
        lon: 17.95,
        latitude: 59.75,
        longitude: 17.95,
        track: 45,
        heading: 45,
        altitude: 35000,
        ground_speed: 450,
        squawk: '1234',
        aircraft_code: 'A320',
        registration: 'SE-ABC',
        origin_airport_iata: 'ARN',
        destination_airport_iata: 'CPH',
        orig_iata: 'ARN',
        dest_iata: 'CPH',
        airline_iata: 'SK',
        airline_icao: 'SAS',
        fr24_id: 'mock-fr24-1',
        timestamp: new Date().toISOString()
    },
    {
        flight_id: 'mock-2',
        callsign: 'DLH456',
        flight_number: 'LH456',
        flight: 'LH456',
        lat: 59.70,
        lon: 18.10,
        latitude: 59.70,
        longitude: 18.10,
        track: 180,
        heading: 180,
        altitude: 28000,
        ground_speed: 420,
        squawk: '2345',
        aircraft_code: 'B738',
        registration: 'D-ABCD',
        origin_airport_iata: 'FRA',
        destination_airport_iata: 'ARN',
        orig_iata: 'FRA',
        dest_iata: 'ARN',
        airline_iata: 'LH',
        airline_icao: 'DLH',
        fr24_id: 'mock-fr24-2',
        timestamp: new Date().toISOString()
    },
    {
        flight_id: 'mock-3',
        callsign: 'NAX789',
        flight_number: 'DY789',
        flight: 'DY789',
        lat: 59.60,
        lon: 17.80,
        latitude: 59.60,
        longitude: 17.80,
        track: 270,
        heading: 270,
        altitude: 32000,
        ground_speed: 440,
        squawk: '3456',
        aircraft_code: 'B737',
        registration: 'LN-XYZ',
        origin_airport_iata: 'OSL',
        destination_airport_iata: 'ARN',
        orig_iata: 'OSL',
        dest_iata: 'ARN',
        airline_iata: 'DY',
        airline_icao: 'NAX',
        fr24_id: 'mock-fr24-3',
        timestamp: new Date().toISOString()
    },
    {
        flight_id: 'mock-4',
        callsign: 'BAW321',
        flight_number: 'BA321',
        flight: 'BA321',
        lat: 59.80,
        lon: 18.20,
        latitude: 59.80,
        longitude: 18.20,
        track: 90,
        heading: 90,
        altitude: 38000,
        ground_speed: 480,
        squawk: '4567',
        aircraft_code: 'A321',
        registration: 'G-EFGH',
        origin_airport_iata: 'LHR',
        destination_airport_iata: 'ARN',
        orig_iata: 'LHR',
        dest_iata: 'ARN',
        airline_iata: 'BA',
        airline_icao: 'BAW',
        fr24_id: 'mock-fr24-4',
        timestamp: new Date().toISOString()
    }
];
